
package docente;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import proyectosistemaexamenes.JFormInicio;

/**
 *
 * @author ALEJANDRO
 */
public class JFormDocente extends javax.swing.JFrame {
    private static JFormDocente  instance;

   

    /**
     * Creates new form JFormDocente
     */
    public JFormDocente() {
        initComponents();
        setLocationRelativeTo(null);
        
        // Añadir ícono al botón Cerrar Sesión
      btnCerrarSesion.setIcon(new ImageIcon(getClass().getResource("/iconos/icono_cerrar.png")));
      btnCerrarSesion.setHorizontalTextPosition(SwingConstants.LEFT); // Texto a la izquierda
      btnCerrarSesion.setIconTextGap(5); //separar texto del icono
        
        // Añadir efecto hover a cada botón
    Color btnColor = new Color(0, 102, 204); // Azul original
    Color btnHoverColor = new Color(0, 82, 164); // Azul más oscuro
    btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            btnCerrarSesion.setBackground(btnHoverColor);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnCerrarSesion.setBackground(btnColor);
        }
    });

    btnCrearExamen.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            btnCrearExamen.setBackground(btnHoverColor);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnCrearExamen.setBackground(btnColor);
        }
    });

    btnAnalisis.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            btnAnalisis.setBackground(btnHoverColor);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnAnalisis.setBackground(btnColor);
        }
    });
    
    btnCalificaciones.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            btnCalificaciones.setBackground(btnHoverColor);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnCalificaciones.setBackground(btnColor);
        }
    });

    }
    
       public static JFormDocente getInstance() {
        if (instance == null) {
            instance = new JFormDocente();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblBienvenido = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnCrearExamen = new javax.swing.JButton();
        btnCalificaciones = new javax.swing.JButton();
        btnAnalisis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PANEL DOCENTE");

        lblBienvenido.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(0, 0, 0));
        lblBienvenido.setText("Bienvenido, [Nombre]");

        btnCerrarSesion.setBackground(new java.awt.Color(0, 102, 204));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnCrearExamen.setBackground(new java.awt.Color(0, 102, 204));
        btnCrearExamen.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnCrearExamen.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearExamen.setText("Crear Exámen");
        btnCrearExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearExamenActionPerformed(evt);
            }
        });

        btnCalificaciones.setBackground(new java.awt.Color(0, 102, 204));
        btnCalificaciones.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnCalificaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnCalificaciones.setText("Ver Calificaciones");
        btnCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificacionesActionPerformed(evt);
            }
        });

        btnAnalisis.setBackground(new java.awt.Color(0, 102, 204));
        btnAnalisis.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnAnalisis.setForeground(new java.awt.Color(255, 255, 255));
        btnAnalisis.setText("Analisis Preguntas");
        btnAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalisisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAnalisis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCalificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrearExamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBienvenido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesion)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBienvenido)
                    .addComponent(btnCerrarSesion))
                .addGap(30, 30, 30)
                .addComponent(btnCrearExamen)
                .addGap(40, 40, 40)
                .addComponent(btnCalificaciones)
                .addGap(39, 39, 39)
                .addComponent(btnAnalisis)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        JFormInicio iniciarSesion = new JFormInicio();
        iniciarSesion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnCrearExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearExamenActionPerformed
        // TODO add your handling code here:
        JFormD_CrearExamen crearExamen = new JFormD_CrearExamen();
        crearExamen.setVisible(true);
        this.dispose();
        
        
     
    }//GEN-LAST:event_btnCrearExamenActionPerformed

    private void btnCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificacionesActionPerformed
        // TODO add your handling code here:
        JFormD_VerCalificaciones Calificaciones = new JFormD_VerCalificaciones();
        Calificaciones.setVisible(true);
        this.dispose();
        
      
        
    }//GEN-LAST:event_btnCalificacionesActionPerformed

    private void btnAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisisActionPerformed
        // TODO add your handling code here:
        JFormD_AnalisisPregunta analisisPregunta = new JFormD_AnalisisPregunta();
        analisisPregunta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAnalisisActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalisis;
    private javax.swing.JButton btnCalificaciones;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCrearExamen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBienvenido;
    // End of variables declaration//GEN-END:variables
}
