
package estudiante;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import proyectosistemaexamenes.JFormInicio;

/**
 *
 * @author ALEJANDRO
 */
public class JFormEstudiante extends javax.swing.JFrame {
    private static JFormEstudiante  instance;

    

    
    public JFormEstudiante() {
        initComponents();
        setLocationRelativeTo(null);
        
           // Añadir ícono al botón Examen
      btnHacerExamen.setIcon(new ImageIcon(getClass().getResource("/iconos/icono_examen.png")));
      btnHacerExamen.setHorizontalTextPosition(SwingConstants.LEFT); // Texto a la izquierda
      btnHacerExamen.setIconTextGap(5); //separar texto del icono
      
       // Añadir ícono al botón Cerrar Sesión
      btnCerrarSesion.setIcon(new ImageIcon(getClass().getResource("/iconos/icono_cerrar.png")));
      btnCerrarSesion.setHorizontalTextPosition(SwingConstants.LEFT); // Texto a la izquierda
      btnCerrarSesion.setIconTextGap(5); //separar texto del icono
      
       // Añadir ícono al botón Ver Examenes
      btnVerExamenes.setIcon(new ImageIcon(getClass().getResource("/iconos/icono_examenes.png")));
      btnVerExamenes.setHorizontalTextPosition(SwingConstants.LEFT); // Texto a la izquierda
      btnVerExamenes.setIconTextGap(5); //separar texto del icono
      
       // Añadir ícono al botón Ver Resultados
      btnResultados.setIcon(new ImageIcon(getClass().getResource("/iconos/icono_resultados.png")));
      btnResultados.setHorizontalTextPosition(SwingConstants.LEFT); // Texto a la izquierda
      btnResultados.setIconTextGap(5); //separar texto del icono
   

    // Añadir efecto hover a cada botón
    Color btnColor = new Color(0, 102, 204); // Azul original
    Color btnHoverColor = new Color(0, 82, 164); // Azul más oscuro
    btnVerExamenes.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            btnVerExamenes.setBackground(btnHoverColor);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnVerExamenes.setBackground(btnColor);
        }
    });

    btnResultados.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            btnResultados.setBackground(btnHoverColor);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnResultados.setBackground(btnColor);
        }
    });

    btnHacerExamen.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            btnHacerExamen.setBackground(btnHoverColor);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnHacerExamen.setBackground(btnColor);
        }
    });

    btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            btnCerrarSesion.setBackground(btnHoverColor);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnCerrarSesion.setBackground(btnColor);
        }
    });

}
    
     public static JFormEstudiante getInstance() {
        if (instance == null) {
            instance = new JFormEstudiante();
        }
        return instance;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblBienvenido = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnVerExamenes = new javax.swing.JButton();
        btnResultados = new javax.swing.JButton();
        btnHacerExamen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PANEL ESTUDIANTE");

        lblBienvenido.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(0, 0, 0));
        lblBienvenido.setText("Bienvenido, [Nombre]");

        btnCerrarSesion.setBackground(new java.awt.Color(0, 102, 204));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnVerExamenes.setBackground(new java.awt.Color(0, 102, 204));
        btnVerExamenes.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnVerExamenes.setForeground(new java.awt.Color(255, 255, 255));
        btnVerExamenes.setText("Ver Examenes");
        btnVerExamenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerExamenesActionPerformed(evt);
            }
        });

        btnResultados.setBackground(new java.awt.Color(0, 102, 204));
        btnResultados.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnResultados.setForeground(new java.awt.Color(255, 255, 255));
        btnResultados.setText("Ver Resultados");
        btnResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosActionPerformed(evt);
            }
        });

        btnHacerExamen.setBackground(new java.awt.Color(0, 102, 204));
        btnHacerExamen.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnHacerExamen.setForeground(new java.awt.Color(255, 255, 255));
        btnHacerExamen.setText("Realizar Examen");
        btnHacerExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHacerExamenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnHacerExamen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnResultados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerExamenes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBienvenido)
                            .addComponent(btnCerrarSesion)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(30, 30, 30)
                .addComponent(btnVerExamenes)
                .addGap(30, 30, 30)
                .addComponent(btnResultados)
                .addGap(30, 30, 30)
                .addComponent(btnHacerExamen)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerExamenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerExamenesActionPerformed
        // TODO add your handling code here:
        JFormE_VerExamenes verExamenes = new JFormE_VerExamenes();
        verExamenes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVerExamenesActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        JFormInicio iniciarSesion = new JFormInicio();
        iniciarSesion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosActionPerformed
        // TODO add your handling code here:
        JFormE_VerResultados verResultados = new JFormE_VerResultados();
        verResultados.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnResultadosActionPerformed

    private void btnHacerExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHacerExamenActionPerformed
        // TODO add your handling code here:
        JFormE_RealizarExamen realizarExamen = new JFormE_RealizarExamen("estudiante");
        realizarExamen.setVisible(true);
        this.dispose();
        
       
    }//GEN-LAST:event_btnHacerExamenActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnHacerExamen;
    private javax.swing.JButton btnResultados;
    private javax.swing.JButton btnVerExamenes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBienvenido;
    // End of variables declaration//GEN-END:variables
}
